---
name: Lint

on: [push, pull_request]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    # check why is failing and change afterwards
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Lint Yaml
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: tests/regression/tests/**/*.yaml
          config_file: .yamllint.yml

      - name: Linelint
        uses: fernandrone/linelint@master
        id: linelint

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: "Check CRS syntax"
        run: |
          python -V
          pip install --upgrade setuptools
          pip install -r tests/integration/requirements.txt
          git clone https://github.com/CRS-support/secrules_parsing
          pip install -r secrules_parsing/requirements.txt
          python secrules_parsing/secrules_parser.py -c -f rules/*.conf
