---
name: Test Ruleset against matrix

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'

jobs:
  run-testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7, 3.6]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Check syntax"
        run: |
          pip3 install -r tests/integration/requirements.txt
          git clone https://github.com/CRS-support/secrules_parsing
          pip3 install -r secrules_parsing/requirements.txt
          python3 secrules_parsing/secrules_parser.py -c -f rules/*.conf
          py.test -vs tests/integration/format_tests.py

      - name: "Run ftw, run"
        env:
          LOGDIR: /var/log/apache2
          CONFIG: 2.9-apache
        run: |
          docker run -ti -e PARANOIA=5 -d -p 80:80 \
            --volume "${LOGDIR}":"${LOGDIR}" \
            --volume "${GITHUB_WORKSPACE}"/rules:/opt/owasp-crs/rules
            --name "${GITHUB_RUN_ID}" modsecurity-crs-"${{ matrix.config }}"
          docker ps | grep -q modsecurity-crs
          if [[ $? -ne 0 ]]; then
            docker logs "${GITHUB_RUN_ID}"
            docker rm -f "${GITHUB_RUN_ID}"
            exit 1
          fi
          pip3 install -r tests/regression/requirements.txt
          py.test -vs tests/regression/CRS_Tests.py \
            --config="${{ matrix.config }}" \
            --ruledir_recurse=tests/regression/tests
           docker rm -f "${GITHUB_RUN_ID}"
